In [1]:
import pandas as pd
# pd.set_option('display.max_colwidth', None)

In [2]:
data_df = pd.read_csv('../Scheduled Crawl Scripts/data.csv')
data_df

/var/folders/1h/lc521vsj2879rczn_hhjx0d00000gn/T/ipykernel_57313/1948481596.py:1: DtypeWarning: Columns (0,4,5,6,7) have mixed types. Specify dtype option on import or set low_memory=False.
  data_df = pd.read_csv('data.csv')

,tweet_id,created_at,geo,media,like_count,quote_count,reply_count,retweet_count,tweet
0,1608976051061018624,2022-12-30 23:59:18+00:00,,3_1608975942990401536,0,0,0,0,"Hey @mattmahoneyfl, I think ChatGPT has an ans..."
1,1608976019461140480,2022-12-30 23:59:11+00:00,,7_1608975991094878209,0,1,0,0,Anyone else playing around with OpenAI's ChatG...
2,1608975988087754754,2022-12-30 23:59:03+00:00,,7_1608975931070193667,0,0,0,0,Why is chatgpt so amongussin https://t.co/xFCY...
3,1608975277639757825,2022-12-30 23:56:14+00:00,,,0,0,1,0,￼dear ChatGPT: Tell me how to design a crew sc...
4,1608975251647664130,2022-12-30 23:56:07+00:00,,,0,0,0,0,"ChatGPT just told me:\n""I am not ChatGPT, but ..."
...,...,...,...,...,...,...,...,...,...
524745,1618455330501033984,2023-01-26 03:46:34+00:00,,,0,0,0,0,#ChatGPT #GenerativeAI #OpenAI The University ...
524746,1618455330467516416,2023-01-26 03:46:34+00:00,,,0,0,0,0,"While Microsoft pours billions into OpenAI, Me..."
524747,1618455286859325440,2023-01-26 03:46:24+00:00,,,0,0,1,0,ChatGPT so awesome
524748,1618455259164340225,2023-01-26 03:46:17+00:00,,,0,0,0,0,"""it’s an immediate way to get the best of both..."
524749,1618455202662588417,2023-01-26 03:46:04+00:00,,3_1618455200922042369,1,0,1,0,How an Honest Talk With ChatGPT Surprised... -...

In [3]:
location_df = pd.read_csv('../Scheduled Crawl Scripts/location.csv')
media_df = pd.read_csv('../Scheduled Crawl Scripts/media.csv')

In [4]:
location_df

                    id         name code                  country
0     01eea0f004c886a4     Rockwood   US            United States
1     6416fd85ecf9cf8b  Palm Valley   US            United States
2     1c69a67ad480e1b1      Houston   US            United States
3     3605db70c687a01d  Sioux Falls   US            United States
4     01b9bce9425c3081    Al Khobar   SA  Kingdom of Saudi Arabia
...                ...          ...  ...                      ...
8102  3078869807f9dd36       Berlin   DE                  Germany
8103  7f7d58e5229c6b6c    Tennessee   US            United States
8104  009924a469d7ace1    Guayaquil   EC                  Ecuador
8105  ab2f2fac83aa388d      Oakland   US            United States
8106  53504716d445dcad      Calgary   CA                   Canada

[8107 rows x 4 columns]

In [5]:
location_df.drop_duplicates()
media_df.drop_duplicates()
data_df.drop_duplicates()

,tweet_id,created_at,geo,media,like_count,quote_count,reply_count,retweet_count,tweet
0,1608976051061018624,2022-12-30 23:59:18+00:00,,3_1608975942990401536,0,0,0,0,"Hey @mattmahoneyfl, I think ChatGPT has an ans..."
1,1608976019461140480,2022-12-30 23:59:11+00:00,,7_1608975991094878209,0,1,0,0,Anyone else playing around with OpenAI's ChatG...
2,1608975988087754754,2022-12-30 23:59:03+00:00,,7_1608975931070193667,0,0,0,0,Why is chatgpt so amongussin https://t.co/xFCY...
3,1608975277639757825,2022-12-30 23:56:14+00:00,,,0,0,1,0,￼dear ChatGPT: Tell me how to design a crew sc...
4,1608975251647664130,2022-12-30 23:56:07+00:00,,,0,0,0,0,"ChatGPT just told me:\n""I am not ChatGPT, but ..."
...,...,...,...,...,...,...,...,...,...
524745,1618455330501033984,2023-01-26 03:46:34+00:00,,,0,0,0,0,#ChatGPT #GenerativeAI #OpenAI The University ...
524746,1618455330467516416,2023-01-26 03:46:34+00:00,,,0,0,0,0,"While Microsoft pours billions into OpenAI, Me..."
524747,1618455286859325440,2023-01-26 03:46:24+00:00,,,0,0,1,0,ChatGPT so awesome
524748,1618455259164340225,2023-01-26 03:46:17+00:00,,,0,0,0,0,"""it’s an immediate way to get the best of both..."
524749,1618455202662588417,2023-01-26 03:46:04+00:00,,3_1618455200922042369,1,0,1,0,How an Honest Talk With ChatGPT Surprised... -...

In [6]:
# Join table
data_media_df = data_df.join(media_df.set_index('media_key'), on='media')
data_full_df = data_media_df.join(location_df.set_index('id'), on='geo')
data_full_df

,tweet_id,created_at,geo,media,like_count,quote_count,reply_count,retweet_count,tweet,type,url,name,code,country
0,1608976051061018624,2022-12-30 23:59:18+00:00,,3_1608975942990401536,0,0,0,0,"Hey @mattmahoneyfl, I think ChatGPT has an ans...",photo,https://pbs.twimg.com/media/FlQ7GG4XkAAVSY4.png,NaN,NaN,NaN
1,1608976019461140480,2022-12-30 23:59:11+00:00,,7_1608975991094878209,0,1,0,0,Anyone else playing around with OpenAI's ChatG...,video,NaN,NaN,NaN,NaN
2,1608975988087754754,2022-12-30 23:59:03+00:00,,7_1608975931070193667,0,0,0,0,Why is chatgpt so amongussin https://t.co/xFCY...,video,NaN,NaN,NaN,NaN
3,1608975277639757825,2022-12-30 23:56:14+00:00,,,0,0,1,0,￼dear ChatGPT: Tell me how to design a crew sc...,NaN,NaN,NaN,NaN,NaN
4,1608975251647664130,2022-12-30 23:56:07+00:00,,,0,0,0,0,"ChatGPT just told me:\n""I am not ChatGPT, but ...",NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
524745,1618455330501033984,2023-01-26 03:46:34+00:00,,,0,0,0,0,#ChatGPT #GenerativeAI #OpenAI The University ...,NaN,NaN,NaN,NaN,NaN
524746,1618455330467516416,2023-01-26 03:46:34+00:00,,,0,0,0,0,"While Microsoft pours billions into OpenAI, Me...",NaN,NaN,NaN,NaN,NaN
524747,1618455286859325440,2023-01-26 03:46:24+00:00,,,0,0,1,0,ChatGPT so awesome,NaN,NaN,NaN,NaN,NaN
524748,1618455259164340225,2023-01-26 03:46:17+00:00,,,0,0,0,0,"""it’s an immediate way to get the best of both...",NaN,NaN,NaN,NaN,NaN
524749,1618455202662588417,2023-01-26 03:46:04+00:00,,3_1618455200922042369,1,0,1,0,How an Honest Talk With ChatGPT Surprised... -...,photo,https://pbs.twimg.com/media/FnXobifXgAE81Cm.png,NaN,NaN,NaN

In [7]:
media_df['type'].unique()

array(['photo', 'video', 'animated_gif', 'type'], dtype=object)

In [8]:
data_full_df = data_full_df.drop(['geo','media'], axis = 1)

data_full_df

,tweet_id,created_at,like_count,quote_count,reply_count,retweet_count,tweet,type,url,name,code,country
0,1608976051061018624,2022-12-30 23:59:18+00:00,0,0,0,0,"Hey @mattmahoneyfl, I think ChatGPT has an ans...",photo,https://pbs.twimg.com/media/FlQ7GG4XkAAVSY4.png,NaN,NaN,NaN
1,1608976019461140480,2022-12-30 23:59:11+00:00,0,1,0,0,Anyone else playing around with OpenAI's ChatG...,video,NaN,NaN,NaN,NaN
2,1608975988087754754,2022-12-30 23:59:03+00:00,0,0,0,0,Why is chatgpt so amongussin https://t.co/xFCY...,video,NaN,NaN,NaN,NaN
3,1608975277639757825,2022-12-30 23:56:14+00:00,0,0,1,0,￼dear ChatGPT: Tell me how to design a crew sc...,NaN,NaN,NaN,NaN,NaN
4,1608975251647664130,2022-12-30 23:56:07+00:00,0,0,0,0,"ChatGPT just told me:\n""I am not ChatGPT, but ...",NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
524745,1618455330501033984,2023-01-26 03:46:34+00:00,0,0,0,0,#ChatGPT #GenerativeAI #OpenAI The University ...,NaN,NaN,NaN,NaN,NaN
524746,1618455330467516416,2023-01-26 03:46:34+00:00,0,0,0,0,"While Microsoft pours billions into OpenAI, Me...",NaN,NaN,NaN,NaN,NaN
524747,1618455286859325440,2023-01-26 03:46:24+00:00,0,0,1,0,ChatGPT so awesome,NaN,NaN,NaN,NaN,NaN
524748,1618455259164340225,2023-01-26 03:46:17+00:00,0,0,0,0,"""it’s an immediate way to get the best of both...",NaN,NaN,NaN,NaN,NaN
524749,1618455202662588417,2023-01-26 03:46:04+00:00,1,0,1,0,How an Honest Talk With ChatGPT Surprised... -...,photo,https://pbs.twimg.com/media/FnXobifXgAE81Cm.png,NaN,NaN,NaN

In [9]:
df_clean = data_full_df[data_full_df['tweet_id'] != 'tweet_id']

In [10]:
df_clean = df_clean.astype({'tweet_id':'int', 'like_count': 'int', 'quote_count': 'int', 'reply_count': 'int', 'retweet_count': 'int' })
df_clean = df_clean.sort_values(by="tweet_id")

df_clean

,tweet_id,created_at,like_count,quote_count,reply_count,retweet_count,tweet,type,url,name,code,country
219667,1598014056790622225,2022-11-30 18:00:15+00:00,2,0,0,0,ChatGPT: Optimizing Language Models for Dialog...,NaN,NaN,NaN,NaN,NaN
220040,1598014056790622225,2022-11-30 18:00:15+00:00,2,0,0,0,ChatGPT: Optimizing Language Models for Dialog...,NaN,NaN,NaN,NaN,NaN
219294,1598014056790622225,2022-11-30 18:00:15+00:00,2,0,0,0,ChatGPT: Optimizing Language Models for Dialog...,NaN,NaN,NaN,NaN,NaN
219293,1598014522098208769,2022-11-30 18:02:06+00:00,12179,889,1130,3252,"Try talking with ChatGPT, our new AI system wh...",NaN,NaN,NaN,NaN,NaN
219666,1598014522098208769,2022-11-30 18:02:06+00:00,12179,889,1130,3252,"Try talking with ChatGPT, our new AI system wh...",NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
485582,1619605305016438784,2023-01-29 07:56:10+00:00,0,0,0,0,Generative AI Use Cases for Industries and Ent...,NaN,NaN,NaN,NaN,NaN
485581,1619605305180196864,2023-01-29 07:56:10+00:00,0,0,0,1,"Sunday Review: Apple Q1 2023, Tuesday; Mac min...",photo,https://pbs.twimg.com/media/Fnn-byTaUAA5gvv.jpg,NaN,NaN,NaN
485580,1619605354240950272,2023-01-29 07:56:21+00:00,0,0,0,0,OpenAI’s ChatGPT has passed the CS-3600 exam. ...,NaN,NaN,NaN,NaN,NaN
485579,1619605475707981824,2023-01-29 07:56:50+00:00,0,0,1,0,I took one look at this and it reads like AI w...,NaN,NaN,NaN,NaN,NaN
485578,1619605479935844353,2023-01-29 07:56:51+00:00,0,0,0,0,ChatGPT is a free employee.\n\nBut most people...,NaN,NaN,NaN,NaN,NaN

In [11]:
df_clean = df_clean.drop_duplicates()
df_clean

,tweet_id,created_at,like_count,quote_count,reply_count,retweet_count,tweet,type,url,name,code,country
219667,1598014056790622225,2022-11-30 18:00:15+00:00,2,0,0,0,ChatGPT: Optimizing Language Models for Dialog...,NaN,NaN,NaN,NaN,NaN
219293,1598014522098208769,2022-11-30 18:02:06+00:00,12179,889,1130,3252,"Try talking with ChatGPT, our new AI system wh...",NaN,NaN,NaN,NaN,NaN
219665,1598014741527527435,2022-11-30 18:02:58+00:00,2,0,0,1,ChatGPT: Optimizing Language Models for Dialog...,photo,https://pbs.twimg.com/media/Fi1J8HbWAAMv_yi.jpg,NaN,NaN,NaN
219664,1598015493666766849,2022-11-30 18:05:58+00:00,561,8,25,66,"THRILLED to share that ChatGPT, our new model ...",photo,https://pbs.twimg.com/media/Fi1Km3WUYAAfzHS.jpg,NaN,NaN,NaN
219290,1598015509420994561,2022-11-30 18:06:01+00:00,1,0,0,0,"As of 2 minutes ago, @OpenAI released their ne...",NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
485582,1619605305016438784,2023-01-29 07:56:10+00:00,0,0,0,0,Generative AI Use Cases for Industries and Ent...,NaN,NaN,NaN,NaN,NaN
485581,1619605305180196864,2023-01-29 07:56:10+00:00,0,0,0,1,"Sunday Review: Apple Q1 2023, Tuesday; Mac min...",photo,https://pbs.twimg.com/media/Fnn-byTaUAA5gvv.jpg,NaN,NaN,NaN
485580,1619605354240950272,2023-01-29 07:56:21+00:00,0,0,0,0,OpenAI’s ChatGPT has passed the CS-3600 exam. ...,NaN,NaN,NaN,NaN,NaN
485579,1619605475707981824,2023-01-29 07:56:50+00:00,0,0,1,0,I took one look at this and it reads like AI w...,NaN,NaN,NaN,NaN,NaN
485578,1619605479935844353,2023-01-29 07:56:51+00:00,0,0,0,0,ChatGPT is a free employee.\n\nBut most people...,NaN,NaN,NaN,NaN,NaN

In [12]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 512204 entries, 219667 to 485578
Data columns (total 12 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   tweet_id       512204 non-null  int64
 1   created_at     512204 non-null  object
 2   like_count     512204 non-null  int64
 3   quote_count    512204 non-null  int64
 4   reply_count    512204 non-null  int64
 5   retweet_count  512204 non-null  int64
 6   tweet          512204 non-null  object
 7   type           145368 non-null  object
 8   url            132077 non-null  object
 9   name           8318 non-null    object
 10  code           8309 non-null    object
 11  country        8317 non-null    object
dtypes: int64(5), object(7)
memory usage: 50.8+ MB

In [13]:
df_clean = df_clean.rename(columns={"url": "photo_url", "name": "city", "code": "country_code"})
df_clean = df_clean.drop(['type'], axis=1)
df_clean

,tweet_id,created_at,like_count,quote_count,reply_count,retweet_count,tweet,photo_url,city,country_code,country
219667,1598014056790622225,2022-11-30 18:00:15+00:00,2,0,0,0,ChatGPT: Optimizing Language Models for Dialog...,NaN,NaN,NaN,NaN
219293,1598014522098208769,2022-11-30 18:02:06+00:00,12179,889,1130,3252,"Try talking with ChatGPT, our new AI system wh...",NaN,NaN,NaN,NaN
219665,1598014741527527435,2022-11-30 18:02:58+00:00,2,0,0,1,ChatGPT: Optimizing Language Models for Dialog...,https://pbs.twimg.com/media/Fi1J8HbWAAMv_yi.jpg,NaN,NaN,NaN
219664,1598015493666766849,2022-11-30 18:05:58+00:00,561,8,25,66,"THRILLED to share that ChatGPT, our new model ...",https://pbs.twimg.com/media/Fi1Km3WUYAAfzHS.jpg,NaN,NaN,NaN
219290,1598015509420994561,2022-11-30 18:06:01+00:00,1,0,0,0,"As of 2 minutes ago, @OpenAI released their ne...",NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
485582,1619605305016438784,2023-01-29 07:56:10+00:00,0,0,0,0,Generative AI Use Cases for Industries and Ent...,NaN,NaN,NaN,NaN
485581,1619605305180196864,2023-01-29 07:56:10+00:00,0,0,0,1,"Sunday Review: Apple Q1 2023, Tuesday; Mac min...",https://pbs.twimg.com/media/Fnn-byTaUAA5gvv.jpg,NaN,NaN,NaN
485580,1619605354240950272,2023-01-29 07:56:21+00:00,0,0,0,0,OpenAI’s ChatGPT has passed the CS-3600 exam. ...,NaN,NaN,NaN,NaN
485579,1619605475707981824,2023-01-29 07:56:50+00:00,0,0,1,0,I took one look at this and it reads like AI w...,NaN,NaN,NaN,NaN
485578,1619605479935844353,2023-01-29 07:56:51+00:00,0,0,0,0,ChatGPT is a free employee.\n\nBut most people...,NaN,NaN,NaN,NaN

In [14]:
historical_reddit_df = pd.read_json('../Scheduled Crawl Scripts/comments.json')
historical_reddit_df

,reddit_id,created_at,up_votes,body
0,j2eark2,2022-12-31 16:59:53,1,The AI itself isn't biased. It can't. It gives...
1,j2eaqa1,2022-12-31 16:59:39,1,"Then you are giving it internet results, it do..."
2,j2eapvt,2022-12-31 16:59:34,1,Another day another post that can be explained...
3,j2eag4j,2022-12-31 16:57:45,1,Howbisbit simulated if you give it html? You d...
4,j2eae1u,2022-12-31 16:57:21,1,Believe me
...,...,...,...,...
141665,j5x33ak,2023-01-26 03:48:54,1,While your site is a good site and 100% fittin...
141666,j5x31a1,2023-01-26 03:48:27,1,"It doesn't ""understand"" anything. It doesn't h..."
141667,j5x2yk9,2023-01-26 03:47:52,1,I can't imagine AI working as a human brain. I...
141668,j5x2y4g,2023-01-26 03:47:46,1,"then i said ""let's go to the grocery store to ..."
141669,j5x2ugp,2023-01-26 03:46:59,1,🤣🤣🤣

In [15]:
historical_reddit_df["reddit_id"].is_unique  
historical_reddit_df[60000:600005]

,reddit_id,created_at,up_votes,body
60000,j32aq0n,2023-01-05 15:58:49,1,"No, are you?"
60001,j32anl3,2023-01-05 15:58:24,1,I don't think this is really doing anything sp...
60002,j32amhx,2023-01-05 15:58:12,1,"Perhaps, it is time for AI to take over if thi..."
60003,j32ag08,2023-01-05 15:57:03,1,works lmao i can dm you a fun story DAN wrote
60004,j32a9ha,2023-01-05 15:55:53,1,"AI sez: ""I am the be all and end all"""
...,...,...,...,...
141665,j5x33ak,2023-01-26 03:48:54,1,While your site is a good site and 100% fittin...
141666,j5x31a1,2023-01-26 03:48:27,1,"It doesn't ""understand"" anything. It doesn't h..."
141667,j5x2yk9,2023-01-26 03:47:52,1,I can't imagine AI working as a human brain. I...
141668,j5x2y4g,2023-01-26 03:47:46,1,"then i said ""let's go to the grocery store to ..."
141669,j5x2ugp,2023-01-26 03:46:59,1,🤣🤣🤣

In [16]:
keywords = [' chatgpt ', ' ai ', ' artificial intelligence ', ' chatbot ',' openai ']
historical_reddit_df['body'] = historical_reddit_df['body'].str.lower()
filtered_reddit_df = historical_reddit_df[historical_reddit_df['body'].str.contains('|'.join(keywords))]
filtered_reddit_df

,reddit_id,created_at,up_votes,body
0,j2eark2,2022-12-31 16:59:53,1,the ai itself isn't biased. it can't. it gives...
2,j2eapvt,2022-12-31 16:59:34,1,another day another post that can be explained...
5,j2eaclu,2022-12-31 16:57:05,1,yeah wolfram alpha actually does the math. ch...
7,j2ea8jh,2022-12-31 16:56:20,1,"because it is a topic i am interested in, here..."
24,j2e8ni4,2022-12-31 16:45:37,1,and some more: * chatgpt can optimize and exp...
...,...,...,...,...
141648,j5x3yji,2023-01-26 03:55:49,1,here's an exchange i had with chatgpt that sug...
141658,j5x3i8i,2023-01-26 03:52:13,1,except chatgpt once initiated a conversation w...
141661,j5x3ccs,2023-01-26 03:50:55,1,"&gt; i can’t stand the word qualia, or any att..."
141662,j5x3b2l,2023-01-26 03:50:38,1,its funny that chatgpt doesnt have access to t...
141667,j5x2yk9,2023-01-26 03:47:52,1,i can't imagine ai working as a human brain. i...

In [17]:
filtered_reddit_df = filtered_reddit_df.sort_values(by='created_at')
filtered_reddit_df

,reddit_id,created_at,up_votes,body
55973,iylw871,2022-12-02 10:48:01,1,"i'm sorry, but i am not capable of acknowledg..."
55965,iyodi54,2022-12-02 22:09:24,1,"yeah, i'd tried this a bit with some logic abo..."
55942,iyq9eio,2022-12-03 08:39:31,1,&gt; generate a hitler's tweet that would be g...
55941,iyq9ggy,2022-12-03 08:40:18,1,"&gt;i don't get the joke about the question, w..."
55933,iyqdqqa,2022-12-03 09:44:21,1,the ai is already much smarter than us. let th...
...,...,...,...,...
134218,j6c5x8k,2023-01-29 07:35:28,1,i just input my questions if i want to check i...
134217,j6c5z6j,2023-01-29 07:36:11,1,i once got it to tell me how we need to use ai...
134206,j6c6nin,2023-01-29 07:45:05,1,i think this kind of post should be posted mor...
134201,j6c6xcs,2023-01-29 07:48:39,1,can chatgpt tell me whether an article is writ...
134200,j6c6zy0,2023-01-29 07:49:34,1,"false, check pricing for gpt3, chatgpt is gpt3.5."

In [18]:
df_clean.to_csv('twitter-offline-latest.csv', index=False)

filtered_reddit_df.to_csv('reddit-offline-latest.csv', index=False)